/**
 * Plane-Aware Emission Formatters
 * 
 * Implements the C1/C2/C3 Emission pattern where every output
 * is simultaneously optimized for three audiences:
 * - C1 (Narrative): Human readers
 * - C2 (Wisdom): AI agents
 * - C3 (Infrastructure): Machines/pipelines
 * 
 * @module resonance-kit/src/core/plane-emitter
 */

/**
 * Emission plane definitions
 */
export const PLANES = {
    C1: {
        id: 'C1',
        name: 'Narrative Plane',
        audience: 'Human readers',
        format: 'HTML/Dashboard',
        description: 'Rich visual presentation for human consumption'
    },
    C2: {
        id: 'C2',
        name: 'Wisdom Plane',
        audience: 'AI agents',
        format: 'Markdown/YAML',
        description: 'Structured content for agent reasoning'
    },
    C3: {
        id: 'C3',
        name: 'Infrastructure Plane',
        audience: 'Machines/pipelines',
        format: 'JSON/Protocol Buffers',
        description: 'Machine-parseable data for automation'
    }
};

/**
 * Format result for the Narrative Plane (C1)
 * Human-readable HTML/dashboard format
 * @param {Object} result - Audit or analysis result
 * @returns {string} HTML-formatted output
 */
export function formatC1(result) {
    const { title, summary, metrics, recommendations } = result;

    return `<!DOCTYPE html>
<html>
<head>
  <meta charset="UTF-8">
  <title>${title || 'SYNTHAI Report'}</title>
  <style>
    body { font-family: system-ui, sans-serif; max-width: 800px; margin: 0 auto; padding: 2rem; }
    .metric { display: inline-block; padding: 1rem; margin: 0.5rem; border-radius: 8px; background: #f5f5f5; }
    .metric-value { font-size: 2rem; font-weight: bold; }
    .metric-label { font-size: 0.875rem; color: #666; }
    .recommendation { padding: 1rem; margin: 0.5rem 0; border-left: 4px solid #3b82f6; background: #eff6ff; }
    .plane-badge { display: inline-block; padding: 0.25rem 0.5rem; background: #10b981; color: white; border-radius: 4px; font-size: 0.75rem; }
  </style>
</head>
<body>
  <span class="plane-badge">C1: Narrative Plane</span>
  <h1>${title || 'Report'}</h1>
  <p>${summary || ''}</p>
  
  ${metrics ? `
  <h2>Metrics</h2>
  <div class="metrics">
    ${Object.entries(metrics).map(([key, value]) => `
      <div class="metric">
        <div class="metric-value">${value}</div>
        <div class="metric-label">${key}</div>
      </div>
    `).join('')}
  </div>
  ` : ''}
  
  ${recommendations ? `
  <h2>Recommendations</h2>
  ${recommendations.map(rec => `<div class="recommendation">${rec}</div>`).join('')}
  ` : ''}
  
  <footer>
    <p><small>Generated by SYNTHAI Resonance-Kit</small></p>
  </footer>
</body>
</html>`;
}

/**
 * Format result for the Wisdom Plane (C2)
 * Agent-consumable Markdown with YAML frontmatter
 * @param {Object} result - Audit or analysis result
 * @returns {string} Markdown-formatted output
 */
export function formatC2(result) {
    const { title, summary, metrics, recommendations, metadata } = result;

    return `---
plane: C2
audience: agent
title: "${title || 'Report'}"
generated: "${new Date().toISOString()}"
${metadata ? Object.entries(metadata).map(([k, v]) => `${k}: ${JSON.stringify(v)}`).join('\n') : ''}
---

# ${title || 'Report'}

> **Plane**: C2 (Wisdom) | **Audience**: AI Agents

## Summary

${summary || 'No summary provided.'}

${metrics ? `
## Metrics

| Metric | Value |
|:-------|:------|
${Object.entries(metrics).map(([key, value]) => `| ${key} | ${value} |`).join('\n')}
` : ''}

${recommendations ? `
## Recommendations

${recommendations.map((rec, i) => `${i + 1}. ${rec}`).join('\n')}
` : ''}

## Agent Instructions

- Use this data for reasoning about system health
- Reference metrics in deliberation phases
- Cite specific values when generating reports
`;
}

/**
 * Format result for the Infrastructure Plane (C3)
 * Machine-parseable JSON
 * @param {Object} result - Audit or analysis result
 * @returns {string} JSON-formatted output
 */
export function formatC3(result) {
    return JSON.stringify({
        plane: 'C3',
        audience: 'machine',
        version: '1.0.0',
        generated: new Date().toISOString(),
        data: result
    }, null, 2);
}

/**
 * Emit result to specified planes
 * @param {Object} result - Result to emit
 * @param {string[]} planes - Array of plane IDs ['C1', 'C2', 'C3']
 * @returns {Object} Formatted outputs keyed by plane
 */
export function emit(result, planes = ['C1', 'C2', 'C3']) {
    const output = {};

    if (planes.includes('C1')) {
        output.C1 = formatC1(result);
    }
    if (planes.includes('C2')) {
        output.C2 = formatC2(result);
    }
    if (planes.includes('C3')) {
        output.C3 = formatC3(result);
    }

    return output;
}

/**
 * Get file extension for a plane's format
 * @param {string} plane - Plane ID
 * @returns {string} File extension
 */
export function getPlaneExtension(plane) {
    const extensions = {
        C1: '.html',
        C2: '.md',
        C3: '.json'
    };
    return extensions[plane] || '.txt';
}

export default { PLANES, emit, formatC1, formatC2, formatC3, getPlaneExtension };
